# Generated by Django 4.2.3 on 2024-04-18 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=6)),
                ("estoque", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Frutas",
        ),
        migrations.DeleteModel(
            name="Verduras",
        ),
        migrations.RenameField(
            model_name="entrega",
            old_name="dtEntrega",
            new_name="data_entrega",
        ),
        migrations.RenameField(
            model_name="entrega",
            old_name="endrNtrg",
            new_name="endereco_entrega",
        ),
        migrations.RenameField(
            model_name="entrega",
            old_name="nmClnt",
            new_name="nome_cliente",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="prcUnit",
            new_name="preco_unidade",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="qntdd",
            new_name="quantidade",
        ),
        migrations.RenameField(
            model_name="pagamento",
            old_name="mtPgto",
            new_name="metodo_pagamento",
        ),
        migrations.RenameField(
            model_name="pagamento",
            old_name="vlrTotal",
            new_name="valor_total",
        ),
        migrations.RemoveField(
            model_name="item",
            name="nmItm",
        ),
        migrations.CreateModel(
            name="Fruta",
            fields=[
                (
                    "produto_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.produto",
                    ),
                ),
            ],
            bases=("app.produto",),
        ),
        migrations.CreateModel(
            name="Verdura",
            fields=[
                (
                    "produto_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.produto",
                    ),
                ),
            ],
            bases=("app.produto",),
        ),
        migrations.AddField(
            model_name="item",
            name="produto",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.produto",
            ),
        ),
    ]
