# Generated by Django 4.2.3 on 2024-04-18 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_produto_delete_frutas_delete_verduras_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.produto"
            ),
        ),
    ]
