# Generated by Django 4.2.3 on 2024-04-18 23:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_item_produto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagamento",
            name="valor_total",
        ),
    ]
