# Generated by Django 4.2.3 on 2024-04-19 00:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_remove_pagamento_valor_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="preco_unidade",
        ),
    ]
