# Generated by Django 4.2.3 on 2024-04-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_remove_item_preco_unidade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="entrega",
        ),
        migrations.AddField(
            model_name="entrega",
            name="itens",
            field=models.ManyToManyField(related_name="entregas", to="app.item"),
        ),
    ]
