# Generated by Django 4.2.3 on 2024-04-19 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_remove_item_entrega_entrega_itens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="quantidade",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
